"""Workspace + document scaffolding: init, new invoice/quote, expense, contractor.

These write hand-readable YAML (comments preserved on the include-list edits) so
the files stay friendly to edit by hand afterwards.
"""

from __future__ import annotations

import calendar
import re
import shutil
from datetime import date, datetime, timedelta
from pathlib import Path

import yaml

from .config import PACKAGE_DIR, Workspace, load_yaml
from .money import coerce_date

INIT_GITIGNORE = (PACKAGE_DIR.parent / ".gitignore")


# ── numbering ──────────────────────────────────────────────────────

def _prefix(studio: dict) -> str:
    return (studio.get("numbering", {}).get("prefix")
            or studio.get("trade_name")
            or "INV").upper()


def next_number(ws: Workspace, year: int, client_slug: str, doc_type: str = "invoice") -> str:
    """Next sequential number. Invoices: <PREFIX>-<YEAR>-<NNN>-<CLIENT> (scans
    invoices + ledger). Quotes: <PREFIX>-Q-<YEAR>-<NNN>-<CLIENT> (own counter)."""
    prefix = _prefix(ws.studio())
    is_quote = doc_type == "quote"
    infix = "Q-" if is_quote else ""
    pattern = re.compile(rf"^{re.escape(prefix)}-{infix}{year}-(\d{{3}})-")
    max_n = 0
    scan_dir = ws.quotes_dir if is_quote else ws.invoices_dir
    if scan_dir.exists():
        for p in scan_dir.rglob("*.yml"):
            m = pattern.match(str(load_yaml(p).get("number", "")))
            if m:
                max_n = max(max_n, int(m.group(1)))
    if not is_quote:
        # Ledger rows cover voided/historical invoices not on disk.
        for row in (load_yaml(ws.ledger_yml).get("invoices") or []):
            m = pattern.match(str(row.get("number", "")))
            if m:
                max_n = max(max_n, int(m.group(1)))
    return f"{prefix}-{infix}{year}-{max_n + 1:03d}-{client_slug.upper()}"


def _due_from_terms(issue: date, payment_terms: str) -> date:
    m = re.search(r"Net\s*(\d+)", payment_terms or "", re.IGNORECASE)
    return issue + timedelta(days=int(m.group(1)) if m else 30)


def parse_period(value: str) -> dict | None:
    if not value:
        return None
    if ".." not in value:
        raise SystemExit(f"--service-period must be 'YYYY-MM-DD..YYYY-MM-DD', got: {value}")
    start_s, end_s = value.split("..", 1)
    return {
        "start": datetime.strptime(start_s.strip(), "%Y-%m-%d").date(),
        "end": datetime.strptime(end_s.strip(), "%Y-%m-%d").date(),
    }


# ── new invoice / quote ────────────────────────────────────────────

def new_invoice(ws: Workspace, client_slug: str, *, issue_date: str | None = None,
                due_date: str | None = None, service_period: str | None = None,
                number: str | None = None, payment_terms: str | None = None,
                notes: str | None = None, doc_type: str = "invoice") -> Path:
    client = ws.client(client_slug)
    issue = datetime.strptime(issue_date, "%Y-%m-%d").date() if issue_date else date.today()
    contract = client.get("contract", {})
    terms = payment_terms or contract.get("payment_terms") or "Net 30"
    due = datetime.strptime(due_date, "%Y-%m-%d").date() if due_date else _due_from_terms(issue, terms)
    num = number or next_number(ws, issue.year, client_slug, doc_type)
    period = parse_period(service_period) if service_period else None

    invoice: dict = {"number": num, "client": client_slug}
    if doc_type == "quote":
        invoice["type"] = "quote"
    invoice |= {"issue_date": issue, "due_date": due, "payment_terms": terms}
    if period:
        invoice["service_period"] = period
    invoice["line_items"] = client.get("default_line_items") or []
    invoice["subcontractors"] = []
    invoice["expenses"] = []
    invoice["include_expenses"] = []
    invoice["include_contractors"] = []
    invoice["notes"] = notes or ""

    m = re.match(rf"^.+-(\d{{4}})-(\d{{3}})-", num)
    if m:
        seq = f"{m.group(1)}-{m.group(2)}"
        fname = f"q-{seq}.yml" if doc_type == "quote" else f"{seq}.yml"
    else:
        fname = f"{num}.yml"

    base_dir = ws.quotes_dir if doc_type == "quote" else ws.invoices_dir
    out_dir = base_dir / client_slug
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / fname
    if out_path.exists():
        raise SystemExit(f"Refusing to overwrite existing file: {out_path}")

    kind = "quote" if doc_type == "quote" else "new"
    header = (f"# Generated by `backoffice {kind}` — edit freely.\n"
              f"# Client: {client_slug}   Render: backoffice render {client_slug}/{fname[:-4]}\n\n")
    out_path.write_text(header + yaml.safe_dump(invoice, sort_keys=False, allow_unicode=True))
    return out_path


# ── include-list text append (preserves comments) ──────────────────

def append_to_include_list(invoice_path: Path, filename: str, key: str) -> None:
    text = invoice_path.read_text()
    inline_empty = re.compile(rf"^{key}:\s*\[\s*\]\s*$", re.MULTILINE)
    populated = re.compile(rf"^{key}:\s*$", re.MULTILINE)

    if inline_empty.search(text):
        text = inline_empty.sub(f"{key}:\n  - {filename}", text)
    elif populated.search(text):
        lines = text.splitlines()
        new_lines: list[str] = []
        injected = False
        i = 0
        while i < len(lines):
            line = lines[i]
            new_lines.append(line)
            if not injected and re.match(rf"^{key}:\s*$", line):
                j = i + 1
                items: list[str] = []
                while j < len(lines) and (lines[j].startswith("  -") or lines[j].strip() == ""):
                    items.append(lines[j]); j += 1
                while items and items[-1].strip() == "":
                    items.pop()
                items.append(f"  - {filename}")
                new_lines.extend(items)
                injected = True
                i = j
                continue
            i += 1
        text = "\n".join(new_lines)
        if not text.endswith("\n"):
            text += "\n"
    else:
        sep = "" if text.endswith("\n") else "\n"
        text = text + f"{sep}\n{key}:\n  - {filename}\n"
    invoice_path.write_text(text)


def _slugify(text: str, fallback: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or fallback


def _unique(base: Path) -> Path:
    if not base.exists():
        return base
    for i in range(2, 100):
        cand = base.with_name(f"{base.stem}-{i}{base.suffix}")
        if not cand.exists():
            return cand
    raise SystemExit(f"Too many collisions for {base}")


def resolve_invoice(ws: Workspace, arg: str) -> Path:
    """Resolve an invoice OR quote reference to a YAML path."""
    p = Path(arg)
    if p.is_absolute() and p.exists():
        return p
    for c in (ws.root / arg, ws.root / f"{arg}.yml",
              ws.invoices_dir / arg, ws.invoices_dir / f"{arg}.yml",
              ws.quotes_dir / arg, ws.quotes_dir / f"{arg}.yml"):
        if c.exists():
            return c
    raise SystemExit(f"Invoice or quote not found for '{arg}'.")


# ── add expense ────────────────────────────────────────────────────

def add_expense(ws: Workspace, *, invoice: str, vendor: str, amount: float,
                date_: str, description: str = "", category: str = "software",
                receipt: str | None = None, client: str | None = None,
                pre_approved: bool = False, pre_approval_ref: str = "",
                notes: str = "") -> tuple[Path, str]:
    invoice_path = resolve_invoice(ws, invoice)
    client_slug = client or invoice_path.parent.name
    datetime.strptime(date_, "%Y-%m-%d")  # validate

    vslug = _slugify(vendor, "vendor")
    ws.expenses_dir.mkdir(parents=True, exist_ok=True)
    exp_path = _unique(ws.expenses_dir / f"{date_}-{vslug}.yml")

    receipt_rel = ""
    if receipt:
        src = Path(receipt).expanduser()
        if not src.exists():
            raise SystemExit(f"Receipt not found: {src}")
        ws.receipts_dir.mkdir(parents=True, exist_ok=True)
        dst = _unique(ws.receipts_dir / f"{date_}-{vslug}{src.suffix}")
        shutil.copy2(src, dst)
        receipt_rel = f"receipts/{dst.name}"

    data = {
        "date": date_, "vendor": vendor, "category": category,
        "description": description, "amount": float(amount), "currency": "USD",
        "client": client_slug, "billable": True,
        "pre_approved": bool(pre_approved), "pre_approval_ref": pre_approval_ref,
        "receipt": receipt_rel, "notes": notes,
    }
    header = f"# Added via `backoffice expense` on {date.today().isoformat()}.\n\n"
    exp_path.write_text(header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True))
    append_to_include_list(invoice_path, exp_path.name, "include_expenses")
    return invoice_path, exp_path.name


# ── add contractor ─────────────────────────────────────────────────

def add_contractor(ws: Workspace, *, invoice: str, name: str, role: str = "",
                   email: str = "", amount: float | None = None,
                   hours: float | None = None, rate: float | None = None,
                   date_: str, description: str = "", client: str | None = None,
                   pre_approved: bool = False, pre_approval_ref: str = "",
                   agreement: str | None = None, contractor_invoice: str | None = None,
                   notes: str = "") -> tuple[Path, str]:
    if amount is None and not (hours is not None and rate is not None):
        raise SystemExit("Provide amount, OR both hours and rate.")
    invoice_path = resolve_invoice(ws, invoice)
    client_slug = client or invoice_path.parent.name
    datetime.strptime(date_, "%Y-%m-%d")

    cslug = _slugify(name, "contractor")
    ws.contractors_dir.mkdir(parents=True, exist_ok=True)
    ws.receipts_dir.mkdir(parents=True, exist_ok=True)
    c_path = _unique(ws.contractors_dir / f"{date_}-{cslug}.yml")

    def _copy(src_arg, suffix_tag):
        if not src_arg:
            return ""
        src = Path(src_arg).expanduser()
        if not src.exists():
            raise SystemExit(f"File not found: {src}")
        dst = _unique(ws.receipts_dir / f"{date_}-{cslug}-{suffix_tag}{src.suffix}")
        shutil.copy2(src, dst)
        return f"receipts/{dst.name}"

    agreement_rel = _copy(agreement, "agreement")
    invoice_rel = _copy(contractor_invoice, "invoice")

    contractor = {"name": name, "role": role}
    if email:
        contractor["email"] = email
    data: dict = {
        "date": date_, "contractor": contractor, "description": description,
        "currency": "USD", "client": client_slug, "billable": True,
        "pre_approved": bool(pre_approved), "pre_approval_ref": pre_approval_ref,
        "contractor_agreement": agreement_rel, "contractor_invoice": invoice_rel,
        "notes": notes,
    }
    if amount is not None:
        data["amount"] = float(amount)
    if hours is not None:
        data["hours"] = float(hours)
    if rate is not None:
        data["rate"] = float(rate)

    header = f"# Added via `backoffice contractor` on {date.today().isoformat()}.\n\n"
    c_path.write_text(header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True))
    append_to_include_list(invoice_path, c_path.name, "include_contractors")
    return invoice_path, c_path.name


# ── accept a quote → invoice ───────────────────────────────────────

def accept_quote(ws: Workspace, quote_ref: str, *, issue_date: str | None = None,
                 due_date: str | None = None, number: str | None = None,
                 payment_terms: str | None = None) -> tuple[Path, str]:
    """Convert an accepted quote into a real invoice. Returns (path, source_number)."""
    qpath = resolve_invoice(ws, quote_ref)
    q = load_yaml(qpath)
    source_num = str(q.get("number", qpath.stem))
    client_slug = q.get("client") or qpath.parent.name
    client = ws.client(client_slug)

    issue = datetime.strptime(issue_date, "%Y-%m-%d").date() if issue_date else date.today()
    terms = (payment_terms or q.get("payment_terms")
             or client.get("contract", {}).get("payment_terms") or "Net 30")
    due = datetime.strptime(due_date, "%Y-%m-%d").date() if due_date else _due_from_terms(issue, terms)
    num = number or next_number(ws, issue.year, client_slug, "invoice")

    invoice: dict = {"number": num, "client": client_slug,
                     "issue_date": issue, "due_date": due, "payment_terms": terms}
    if q.get("service_period"):
        invoice["service_period"] = q["service_period"]
    invoice["line_items"] = q.get("line_items") or client.get("default_line_items") or []
    invoice["subcontractors"] = q.get("subcontractors") or []
    invoice["expenses"] = q.get("expenses") or []
    invoice["include_expenses"] = q.get("include_expenses") or []
    invoice["include_contractors"] = q.get("include_contractors") or []
    note = f"Converted from quote {source_num}."
    base_notes = (q.get("notes") or "").strip()
    invoice["notes"] = (base_notes + ("\n" if base_notes else "") + note)

    m = re.match(r"^.+-(\d{4})-(\d{3})-", num)
    fname = f"{m.group(1)}-{m.group(2)}.yml" if m else f"{num}.yml"
    out_dir = ws.invoices_dir / client_slug
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / fname
    if out_path.exists():
        raise SystemExit(f"Refusing to overwrite existing file: {out_path}")
    header = f"# Accepted from quote {source_num} on {date.today().isoformat()}.\n\n"
    out_path.write_text(header + yaml.safe_dump(invoice, sort_keys=False, allow_unicode=True))
    return out_path, source_num


# ── recurring billing cycle ────────────────────────────────────────

def _is_recurring(client: dict) -> bool:
    if client.get("recurring") is True:
        return True
    return str((client.get("billing") or {}).get("cycle", "")).lower() == "monthly"


def run_cycle(ws: Workspace, *, month: str | None = None,
              issue_date: str | None = None) -> list[dict]:
    """Generate this month's invoice for every recurring client.

    `month` is 'YYYY-MM' (default: current month). Idempotent — a client that
    already has an invoice covering the month's start is skipped.
    Returns a list of {slug, status, number|path} dicts.
    """
    if month:
        y, m = (int(x) for x in month.split("-")[:2])
    else:
        today = date.today()
        y, m = today.year, today.month
    start = date(y, m, 1)
    end = date(y, m, calendar.monthrange(y, m)[1])
    period_arg = f"{start.isoformat()}..{end.isoformat()}"

    results: list[dict] = []
    if not ws.clients_dir.exists():
        return results
    for cpath in sorted(ws.clients_dir.glob("*.yml")):
        client = load_yaml(cpath)
        slug = client.get("slug") or cpath.stem
        if not _is_recurring(client):
            continue
        # Idempotency: an invoice already covering this month → skip.
        existing = None
        cdir = ws.invoices_dir / slug
        if cdir.exists():
            for inv in cdir.glob("*.yml"):
                sp = load_yaml(inv).get("service_period") or {}
                d = coerce_date(sp.get("start"))
                if d == start:
                    existing = inv
                    break
        if existing:
            results.append({"slug": slug, "status": "skipped", "ref": existing.stem})
            continue
        path = new_invoice(ws, slug, issue_date=issue_date, service_period=period_arg,
                           notes=f"Recurring invoice — {start.strftime('%B %Y')}.")
        results.append({"slug": slug, "status": "created", "ref": path.stem, "path": path})
    return results


# ── init ───────────────────────────────────────────────────────────

def init_workspace(ws: Workspace, force: bool = False) -> list[Path]:
    """Create a fresh, renderable workspace with a sample client + invoice."""
    if ws.studio_yml.exists() and not force:
        raise SystemExit(f"studio.yml already exists at {ws.studio_yml}. Use --force to add missing pieces.")
    ws.root.mkdir(parents=True, exist_ok=True)
    for d in ("clients", "invoices", "quotes", "expenses", "contractors",
              "receipts", "forms", "contracts"):
        (ws.root / d).mkdir(exist_ok=True)

    written: list[Path] = []

    def _w(path: Path, content: str):
        if path.exists() and not force:
            return
        path.write_text(content)
        written.append(path)

    _w(ws.studio_yml, _SAMPLE_STUDIO)
    _w(ws.root / "studio.local.example.yml", _SAMPLE_STUDIO_LOCAL)
    _w(ws.clients_dir / "acme.yml", _SAMPLE_CLIENT)
    if INIT_GITIGNORE.exists() and not (ws.root / ".gitignore").exists():
        shutil.copy2(INIT_GITIGNORE, ws.root / ".gitignore")
        written.append(ws.root / ".gitignore")

    # First invoice (only if none exist for acme).
    if not (ws.invoices_dir / "acme").exists():
        p = new_invoice(ws, "acme", service_period=None,
                        notes="Thanks for your business. Questions? hello@northwind.example")
        written.append(p)
    return written


_SAMPLE_STUDIO = """\
# Your studio identity. Renders into every invoice.
# Real bank / EIN go in studio.local.yml (gitignored) — keep this file safe to commit.

legal_name: Northwind Studio, LLC
short_name: Northwind Studio
trade_name: NWS
state_of_formation: Delaware

address:
  line1: 100 Example Ave
  city: Anytown
  state: CA
  zip: "90000"
  country: USA

contact:
  phone: 555-010-0100
  email: hello@northwind.example
  website: northwind.example

signer:
  name: Pat Founder
  title: Managing Member

# Branding — theme every invoice without touching the template.
branding:
  accent: "#1f6f5c"
  font: 'ui-sans-serif, -apple-system, "Helvetica Neue", Helvetica, Arial, sans-serif'

# Invoice numbering: <PREFIX>-<YEAR>-<NNN>-<CLIENT>. Prefix falls back to trade_name.
numbering:
  prefix: NWS

# Non-secret tax fields. Put EIN in studio.local.yml if you'd rather not commit it.
tax:
  classification: "Single-member LLC (disregarded entity)"
  w9:
    file: forms/w9.pdf
    label: "W-9"

payment:
  currency: USD
  default_terms: Net 30
  # Bank details live in studio.local.yml — DO NOT put real numbers here.
  check:
    payable_to: Northwind Studio, LLC
    mail_to:
      - Northwind Studio, LLC
      - 100 Example Ave
      - Anytown, CA 90000
"""

_SAMPLE_STUDIO_LOCAL = """\
# studio.local.yml  —  GITIGNORED. Real secrets overlay studio.yml here.
# Copy this file to studio.local.yml and fill in. Values here win over studio.yml.

tax:
  ein: "00-0000000"

payment:
  ach:
    bank_name: Your Bank
    account_type: Business Checking
    account_name: Northwind Studio, LLC
    routing: "000000000"
    account: "000000000000"
  wire:
    routing: ""
    account: "000000000000"
    account_name: Northwind Studio, LLC
"""

_SAMPLE_CLIENT = """\
# A client. Per-invoice files in invoices/acme/ inherit these defaults.

slug: acme

# recurring: true  → `backoffice cycle` generates this client's monthly invoice.
recurring: true

client:
  legal_name: Acme Incorporated
  attn: "Accounts Payable"
  email: ap@acme.example
  address:
    line1: "1 Acme Plaza"
    city: "Metropolis"
    state: "NY"
    zip: "10001"
    country: USA

contract:
  reference: "Master Services Agreement"
  reference_date: 2026-01-01
  contract_ref: "contracts/acme/2026-01-01_msa.md"
  payment_terms: "Net 30"
  subcontractor_cap_per_month: 5000.00

# Recurring lines that default into each new invoice for this client.
default_line_items:
  - description: "Monthly retainer — consulting services"
    quantity: 1
    unit: month
    rate: 8000.00
"""
